# Generated by Django 2.1.15 on 2022-11-26 03:02

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields.related


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('catidad', models.DecimalField(decimal_places=2, max_digits=11)),
                ('producto', models.CharField(max_length=15)),
                ('bl', models.CharField(max_length=20)),
                ('manifiesto', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Buque',
                'verbose_name_plural': 'Buques',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.TextField(max_length=7)),
                ('fechafirma', models.DateField()),
                ('periodo', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=9)),
                ('tipo_empresa', models.TextField(choices=[('Deportes Mixtas', 'Deportes Mixtas'), ('Deportes 100% Cubanas', 'Deportes 100% Cubanas'), ('TCP', 'TCP'), ('CNA', 'CNA'), ('Empresa Extranjera', 'Empresa Extranjera')])),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Comprador',
                'verbose_name_plural': 'Compradores',
            },
        ),
        migrations.CreateModel(
            name='Contenedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('dimenciones', models.TextField(choices=[('20 pies', '20 pies'), ('40 pies', '40 pies')])),
                ('cantidad', models.BigIntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=9)),
                ('embalaje', models.TextField(max_length=150)),
                ('estiba', models.TextField(max_length=150)),
                ('marca', models.TextField(max_length=150)),
                ('mercancia', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Contenedor',
                'verbose_name_plural': 'Contenedores',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('direccion', models.CharField(max_length=100)),
                ('codigo_one', models.IntegerField(verbose_name=django.db.models.fields.related.ForeignKey)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Deportes',
            },
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='operaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_incidencia', models.TextField(choices=[('Sobrante', 'Sobrante'), ('Faltante', 'Faltante'), ('Averias', 'Averias')])),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_orden', models.CharField(max_length=15, verbose_name=django.db.models.fields.related.ForeignKey)),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.BigIntegerField(verbose_name=django.db.models.fields.related.ForeignKey)),
                ('nombre', models.CharField(max_length=10)),
                ('apellidos', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=25)),
                ('telefono', models.BigIntegerField()),
                ('correo', models.EmailField(max_length=25)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Apps.Empresa')),
            ],
            options={
                'verbose_name': 'Receptor',
                'verbose_name_plural': 'Receptores',
            },
        ),
        migrations.CreateModel(
            name='Sello',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_sello', models.CharField(max_length=15)),
                ('material', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_solicitud', models.TextField(choices=[('Origen', 'Origen'), ('Destino', 'Destino')], null=True)),
                ('medio', models.TextField(choices=[('buque', 'Buques'), ('contenedor', 'Contenedores')], default='Buques')),
                ('contrato', models.CharField(max_length=15, verbose_name='Contrato')),
                ('fecha_Solicitud', models.DateField(verbose_name='Fecha de la Solicitud')),
                ('fecha_Inspeccion', models.DateField(verbose_name='Fecha de la Inspeccion')),
                ('vendedor', models.CharField(max_length=60)),
                ('comprador', models.CharField(max_length=60)),
                ('receptor', models.CharField(max_length=60)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apps.Cliente', verbose_name='Cliente')),
                ('servicio', models.ManyToManyField(to='Apps.Servicios', verbose_name='Servicios')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Apps.Empresa')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
            },
        ),
        migrations.AddField(
            model_name='orden',
            name='solicitud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Apps.Solicitud'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apps.Orden'),
        ),
        migrations.AddField(
            model_name='imagenes',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Apps.Orden'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apps.Solicitud'),
        ),
        migrations.AddField(
            model_name='comprador',
            name='empresa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Apps.Empresa'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Apps.Empresa'),
        ),
        migrations.AddField(
            model_name='buque',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apps.Solicitud'),
        ),
    ]
