# Generated by Django 4.1.3 on 2022-11-28 15:46

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields.related


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('apel', models.CharField(max_length=250, verbose_name='Apellido')),
                ('fecha', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('image', models.ImageField(upload_to='deporte')),
            ],
            options={
                'verbose_name': 'atletas',
                'verbose_name_plural': 'atletas',
                'db_table': 'atletas',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.TextField(max_length=7)),
                ('fechafirma', models.DateField()),
                ('periodo', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=9)),
                ('tipo_empresa', models.TextField(choices=[('Deportes Mixtas', 'Deportes Mixtas'), ('Deportes 100% Cubanas', 'Deportes 100% Cubanas'), ('TCP', 'TCP'), ('CNA', 'CNA'), ('Empresa Extranjera', 'Empresa Extranjera')])),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='CodEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=1000, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'codEvento',
                'verbose_name_plural': 'codEventos',
                'db_table': 'codEventos',
            },
        ),
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre del deporte')),
            ],
            options={
                'verbose_name': 'Deporte',
                'verbose_name_plural': 'Deportes',
                'db_table': 'deportes',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre de la disciplina')),
                ('deporte_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apps.deporte')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'disciplina',
                'db_table': 'disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('direccion', models.CharField(max_length=100)),
                ('codigo_one', models.IntegerField(verbose_name=django.db.models.fields.related.ForeignKey)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Deportes',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('sigla', models.CharField(max_length=250, verbose_name='Resultado')),
                ('flag', models.ImageField(upload_to='flags')),
            ],
            options={
                'verbose_name': 'pais',
                'verbose_name_plural': 'paises',
                'db_table': 'paises',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.BigIntegerField(verbose_name=django.db.models.fields.related.ForeignKey)),
                ('nombre', models.CharField(max_length=10)),
                ('apellidos', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=25)),
                ('telefono', models.BigIntegerField()),
                ('correo', models.EmailField(max_length=25)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Sello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_sello', models.CharField(max_length=15)),
                ('material', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Apps.empresa')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_solicitud', models.TextField(choices=[('Origen', 'Origen'), ('Destino', 'Destino')], null=True)),
                ('medio', models.TextField(choices=[('buque', 'Buques'), ('contenedor', 'Contenedores')], default='Buques')),
                ('contrato', models.CharField(max_length=15, verbose_name='Contrato')),
                ('fecha_Solicitud', models.DateField(verbose_name='Fecha de la Solicitud')),
                ('fecha_Inspeccion', models.DateField(verbose_name='Fecha de la Inspeccion')),
                ('vendedor', models.CharField(max_length=60)),
                ('comprador', models.CharField(max_length=60)),
                ('receptor', models.CharField(max_length=60)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apps.cliente', verbose_name='Cliente')),
                ('servicio', models.ManyToManyField(to='Apps.servicios', verbose_name='Servicios')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
            },
        ),
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Apps.empresa')),
            ],
            options={
                'verbose_name': 'Receptor',
                'verbose_name_plural': 'Receptores',
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('result', models.CharField(max_length=1000, verbose_name='Resultado')),
                ('lugar_obtuvo', models.CharField(max_length=250, verbose_name='Lugar')),
                ('observaciones', models.CharField(max_length=10000, verbose_name='Observaciones')),
                ('atleta_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Apps.atleta')),
            ],
            options={
                'verbose_name': 'partido',
                'verbose_name_plural': 'partidos',
                'db_table': 'partidos',
            },
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atleta_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Apps.atleta')),
                ('disciplina_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Apps.disciplina')),
                ('evento_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Apps.codevento')),
            ],
            options={
                'verbose_name': 'participacion',
                'verbose_name_plural': 'participacions',
                'db_table': 'participacions',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_orden', models.CharField(max_length=15, verbose_name=django.db.models.fields.related.ForeignKey)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Apps.solicitud')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_incidencia', models.TextField(choices=[('Sobrante', 'Sobrante'), ('Faltante', 'Faltante'), ('Averias', 'Averias')])),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apps.orden')),
            ],
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='operaciones')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Apps.orden')),
            ],
        ),
        migrations.CreateModel(
            name='Contenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('dimenciones', models.TextField(choices=[('20 pies', '20 pies'), ('40 pies', '40 pies')])),
                ('cantidad', models.BigIntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=9)),
                ('embalaje', models.TextField(max_length=150)),
                ('estiba', models.TextField(max_length=150)),
                ('marca', models.TextField(max_length=150)),
                ('mercancia', models.CharField(max_length=15)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apps.solicitud')),
            ],
            options={
                'verbose_name': 'Contenedor',
                'verbose_name_plural': 'Contenedores',
            },
        ),
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Apps.empresa')),
            ],
            options={
                'verbose_name': 'Comprador',
                'verbose_name_plural': 'Compradores',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Apps.empresa'),
        ),
        migrations.CreateModel(
            name='ClaseDeportiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('siglas', models.CharField(max_length=250, verbose_name='Sigla')),
                ('deporte_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Apps.deporte')),
            ],
            options={
                'verbose_name': 'clased',
                'verbose_name_plural': 'claseds',
                'db_table': 'clases',
            },
        ),
        migrations.CreateModel(
            name='Buque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('catidad', models.DecimalField(decimal_places=2, max_digits=11)),
                ('producto', models.CharField(max_length=15)),
                ('bl', models.CharField(max_length=20)),
                ('manifiesto', models.CharField(max_length=15)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apps.solicitud')),
            ],
            options={
                'verbose_name': 'Buque',
                'verbose_name_plural': 'Buques',
            },
        ),
        migrations.AddField(
            model_name='atleta',
            name='disciplina',
            field=models.ManyToManyField(to='Apps.disciplina'),
        ),
    ]
