# Generated by Django 2.1.15 on 2022-11-26 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0003_atleta_clasedeportiva_partido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='deporte',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='deporte_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Apps.Deporte'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
