# Generated by Django 2.1.15 on 2022-11-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0004_auto_20221126_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('sigla', models.CharField(max_length=250, verbose_name='Resultado')),
                ('flag', models.ImageField(upload_to='flags')),
            ],
            options={
                'verbose_name': 'pais',
                'verbose_name_plural': 'paises',
                'db_table': 'paises',
            },
        ),
        migrations.AddField(
            model_name='partido',
            name='lugar_obtuvo',
            field=models.CharField(default=1, max_length=250, verbose_name='Lugar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partido',
            name='nombre',
            field=models.CharField(default=1, max_length=250, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partido',
            name='result',
            field=models.CharField(max_length=1000, verbose_name='Resultado'),
        ),
    ]
