# Generated by Django 2.1.15 on 2022-11-27 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0005_auto_20221126_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=1000, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'codEvento',
                'verbose_name_plural': 'codEventos',
                'db_table': 'codEventos',
            },
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atleta_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Apps.Atleta')),
                ('disciplina_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Apps.Disciplina')),
                ('evento_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Apps.CodEvento')),
            ],
            options={
                'verbose_name': 'participacion',
                'verbose_name_plural': 'participacions',
                'db_table': 'participacions',
            },
        ),
        migrations.AlterField(
            model_name='clasedeportiva',
            name='siglas',
            field=models.CharField(max_length=250, verbose_name='Sigla'),
        ),
    ]
